server:
  port: 9050
  servlet:
    context-path: /test/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://postgresql://ec2-34-201-95-87.compute-1.amazonaws.com:5432/de2e35775n7ors
    username: picoxbtqdakqpf
    password: bc5ec0dae26e2d3374f70d011fbc82d0c9c689f28587aed98dc61cb0fb05d321
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
